# Generated by Django 4.0.3 on 2022-03-25 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('nombre_equipo', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('potencia_actual', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Dispositivos',
                'db_table': 'Dispositivo',
            },
        ),
        migrations.CreateModel(
            name='StatusDispositivo',
            fields=[
                ('status_dispositivo', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Status de Dispositivos',
                'db_table': 'Status Dispositivo',
            },
        ),
        migrations.CreateModel(
            name='TipoDispositivo',
            fields=[
                ('tipo', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Dispositivo',
                'db_table': 'Tipo Dispositivo',
            },
        ),
        migrations.CreateModel(
            name='LecturaDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potencia_actual', models.IntegerField()),
                ('timestamp_potencia', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ManyToManyField(to='generadores.dispositivo')),
                ('tipo_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generadores.tipodispositivo')),
            ],
            options={
                'verbose_name_plural': 'Lectura Dispositivos',
                'db_table': 'Lectura Dispositivo',
            },
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='status_dispositivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generadores.statusdispositivo'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='tipo_dispositivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generadores.tipodispositivo'),
        ),
    ]
