# Generated by Django 4.0.3 on 2022-03-28 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_dispositivo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Status de Dispositivos',
                'db_table': 'Status Dispositivo',
            },
        ),
        migrations.CreateModel(
            name='TipoDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Dispositivo',
                'db_table': 'Tipo Dispositivo',
            },
        ),
        migrations.CreateModel(
            name='LecturaDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potencia_actual', models.IntegerField()),
                ('timestamp_potencia', models.DateTimeField(auto_now_add=True)),
                ('tipo_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generadores.tipodispositivo')),
            ],
            options={
                'verbose_name_plural': 'Lectura Dispositivos',
                'db_table': 'Lectura Dispositivo',
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=50, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('potenciaactual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potenciaactual', to='generadores.lecturadispositivo')),
                ('status_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generadores.statusdispositivo')),
                ('timestamppotencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timestamppotencia', to='generadores.lecturadispositivo')),
                ('tipo_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generadores.tipodispositivo')),
            ],
            options={
                'verbose_name_plural': 'Dispositivos',
                'db_table': 'Dispositivo',
            },
        ),
    ]
